version: '3.7'

services:
    app:
        container_name: app
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - './client:/app'
            - '/app/node_modules'
        ports:
            - "3000:3000"
        environment: 
            - NODE_ENV=development
    socket:
        container_name: socket
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - "5000:5000"
        environment: 
            - NODE_ENV=development